### PR TITLE
Fix slippage in the calculate buy and sell functions

### PR DESCRIPTION
**Pull request by kongzii**

### CODE REVIEW

**Review by evangriffiths — COMMENTED** [review]
Is this just moving the slippage calculation from the `calculate` functions to the level up, where they are called?

**Comment by evangriffiths** [comment]
> Is this just moving the slippage calculation from the `calculate` functions to the level up, where they are called?

Ah, just seen your comment https://github.com/evangriffiths/prediction-market-agent/pull/11#discussion_r1463126800 !!

**Comment by kongzii** [comment]
> Is this just moving the slippage calculation from the `calculate` functions to the level up, where they are called?

Yes, I think it makes more sense like this, anyway. From the names `omen_calculate_{buy,sell}_amount`, it's not clear they won't return the exact amounts.

**Review by evangriffiths — APPROVED** [review]
Just checked this commit with https://github.com/evangriffiths/prediction-market-agent/pull/11 and it fixes that TODO. Nice!!

**Pull request merged**
